---
autor: "Qiran Chen"
title: "p8105_hw5_qc2336"
output: html_document
  ## github_document
date: "2023-11-07"
---
```{r}
library(tidyverse)
library(dplyr)
library(rvest)
library(purrr)
library(ggplot2)
library(patchwork)
```

## Problem 1
```{r}
homicide=read_csv(file = "./data/homicide-data.csv")

homicide
```
>> The raw data has 52170 observations and 12 variables, including a unique id. The date, the victim's information, where is has happened and the result.

```{r}
homicide=homicide|>
  mutate(city_state=str_c(city,state,sep=", "),
         state = replace(state, state == "wI", "WI"),)

```

```{r}

homicide_n=homicide|> 
  group_by(city_state) |>
  summarize(
    total_homicides = n(),
    unsolved_homicides = sum(disposition %in% "Open/No arrest") + sum(disposition %in% "Closed without arrest")) |>
  tibble()

homicide_n
```

```{r}
hom_unsolved=homicide_n|>
  filter(city_state%in% "Baltimore, MD")|>
  mutate(prop_test = map2(unsolved_homicides, total_homicides, ~prop.test(.x, .y)|>
                            broom::tidy()))  |>
  unnest()|>
  select(city_state, estimate, conf.low,  conf.high)


hom_unsolved
```

```{r}
all_unsolved=homicide_n|>
  mutate(prop_test = map2(unsolved_homicides, total_homicides, ~prop.test(.x, .y)|>
                            broom::tidy()))  |>
  unnest()|>
  select(city_state, estimate, conf.low,  conf.high)

all_unsolved

all_unsolved|>
  mutate(city_state = fct_reorder(city_state, estimate))|>
  ggplot(aes(y=city_state, x=estimate))+
  geom_point()+
  geom_errorbar(aes(xmin = conf.low, xmax = conf.high))

```

## Problem 2

```{r, message=FALSE}
long_data=tibble(files = list.files("data/data 2/"),
    path = str_c("data/data 2/",files))|>
  mutate(data = map(path, read_csv)) |>
  unnest()
```
```{r}
tidy_long=long_data|>
  mutate(files=str_replace(files,".csv",""),
         group = str_sub(files, 1, 3))|>
  pivot_longer(week_1:week_8,
               names_to = "week",
               values_to = "results",
               names_prefix = "week_")|>
  mutate(week=as.numeric(week))|>
  select(-path)


tidy_long
```
```{r}
tidy_long|>
  ggplot(aes(x=week, y=results, color=files))+
  geom_line()+
  facet_grid(~group)+
  ggtitle("Results vs. Week of Control and Experiment Group")

```
>> The graph shows significant increase in results over the 8m weeks. While the result for control stayed relatively the same.

## Problem 3

```{r}
t_test = function(n=30,mu=0, sigma=5) {
  sim_data = tibble( x=rnorm(n=30,mean = mu,sd= sigma))
 
  result=sim_data|>
    t.test() |> 
    broom::tidy() |>
    select(estimate,p.value)
  
  result
}
  
sim_results_df = 
  expand_grid(
    true_mean= 0, 
    iter = 1:5000) |> 
  mutate(
    result = map(true_mean, t_test)) |> 
  unnest(result)
  
```


```{r}

```


